<?php

define('WOOCOMMERCE_CATALOG_ENQUIRY_PLUGIN_TOKEN', 'woocommerce-catalog-enquiry');

define('WOOCOMMERCE_CATALOG_ENQUIRY_TEXT_DOMAIN', 'woocommerce-catalog-enquiry');

define('WOOCOMMERCE_CATALOG_ENQUIRY_PLUGIN_VERSION', '5.0.10');

define('WOOCOMMERCE_CATALOG_ENQUIRY_PRO_SHOP_URL', '');

define('WOOCOMMERCE_CATALOG_ENQUIRY_REST_NAMESPACE', 'catalog/v1');